//;-*- mode: java-*-
/*
                        NLP-Games

   Copyright (C) 2006 Ventura24 S.L.

   License details are included in Ventura24 license file.
 */
// Generated by QueryJ using org/acmsl/queryj/vo/ValueObject.stg at 2013/06/17 06:22
package com.ventura24.nlp.games.vo;

/*
 * Importing some JDK classes.
 */
import java.io.Serializable;
import java.sql.Timestamp;import java.util.Date;

/**
 * Value object for <i>G_PRODUCTS</i>.
 * @author <a href="http://www.acm-sl.org/projects/queryj">QueryJ</a> 
 * @since 2013/06/17 06:22
 */
public interface GProduct
    extends  Serializable
{
    /**
     * Retrieves the <i>G_PRODUCT_ID</i> value.
     * @return such information.
     */
    long getGProductId();

    /**
     * Retrieves the <i>G_PRODUCT_TYPE_ID</i> value.
     * @return such information.
     */
    long getGProductTypeId();

    /**
     * Retrieves the <i>G_BETTOR_ID</i> value.
     * @return such information.
     */
    long getGBettorId();

    /**
     * Retrieves the <i>G_BETTOR_TYPE_ID</i> value.
     * @return such information.
     */
    long getGBettorTypeId();

    /**
     * Retrieves the <i>G_SUBSCRIPTION_ID</i> value.
     * @return such information.
     */
    @Nullable Long getGSubscriptionId();

    /**
     * Retrieves the <i>G_PAYMENT_STATE_ID</i> value.
     * @return such information.
     */
    long getGPaymentStateId();

    /**
     * Retrieves the <i>G_FIRST_DRAW_ID</i> value.
     * @return such information.
     */
    long getGFirstDrawId();

    /**
     * Retrieves the <i>G_LAST_DRAW_ID</i> value.
     * @return such information.
     */
    long getGLastDrawId();

    /**
     * Retrieves the <i>EXTERNAL_ID</i> value.
     * @return such information.
     */
    long getExternalId();

    /**
     * Retrieves the <i>AMOUNT</i> value.
     * @return such information.
     */
    double getAmount();

    /**
     * Retrieves the <i>DURATION</i> value.
     * @return such information.
     */
    long getDuration();

    /**
     * Retrieves the <i>LAST_MODIFIED</i> value.
     * @return such information.
     */
    @NotNull Date getLastModified();

    /**
     * Retrieves the <i>CREATION_DATE</i> value.
     * @return such information.
     */
    @NotNull Date getCreationDate();

}
